import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script async src="https://unpkg.com/react@16/umd/react.development.js"></script>
        <script async src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
        <script async src="https://source.zoom.us/2.18.0/lib/vendor/react-dom.min.js"></script>
        <script async src="https://source.zoom.us/2.18.0/lib/vendor/redux.min.js"></script>
        <script async src="https://source.zoom.us/2.18.0/lib/vendor/redux-thunk.min.js"></script>
        <script async src="https://source.zoom.us/2.18.0/lib/vendor/lodash.min.js"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
